M48
; DRILL file KiCad 10.0.3 date 2026-09-30T18:54:53
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-30T18:54:53+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X4.3689Y-2.8524
T2
X5.1427Y-4.7394
T3
X4.7039Y-3.4823
X6.8787Y-2.8524
M30
